repos:
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        language: system
        entry: npx @biomejs/biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        types_or: [javascript]
